title: Kyle Reid
description: Director, Business Operations @ Help Scout
url: "https://kmreid20.github.io"
baseurl: "/kylereid"

# GitHub Pages
remote_theme: null
plugins: []

# Build
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
